name: Deploy Staging
#run-name: ${{ github.actor }} is staging ${{github.repository}}.

on:
  push:
    branches: [staging]
  workflow_dispatch:

jobs:
  deploy:
    name: Staging Deploy
    runs-on: ubuntu-latest

    steps:
    - name: SSH Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_WPCLIENTS_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVKEY }}

        script: |
          cd ${{ vars.DIRECTORY }}
          git config --global --add safe.directory ${{ vars.DIRECTORY }}
          git fetch
          git checkout staging
          git reset --hard origin/staging